-- Paneru config — niri-like sliding strip. Modifier lanes:
-- Cmd+Option = columns, Ctrl+Option = dynamic workspace rows,
-- Cmd+Ctrl = displays, Cmd+Shift+? = shortcut cheat sheet.
-- Generated by paneru-wm-installer. Edit freely; live reload is on.
--
-- All Paneru keybindings live in BINDINGS below (command vs chord);
-- helpers/generate-shortcuts-json turns this table into the
-- mac-cheatsheet-viewer JSON.

local BINDINGS = {
  -- ─── Window focus (Cmd+Option+Arrows) ───
  ["window focus west"] = "cmd + alt - leftarrow",
  ["window focus east"] = "cmd + alt - rightarrow",
  ["window focus north"] = "cmd + alt - uparrow",
  ["window focus south"] = "cmd + alt - downarrow",

  -- ─── Move window (Cmd+Option+Shift+Arrows) ───
  ["window swap west"] = "cmd + alt + shift - leftarrow",
  ["window swap east"] = "cmd + alt + shift - rightarrow",
  ["window swap north"] = "cmd + alt + shift - uparrow",
  ["window swap south"] = "cmd + alt + shift - downarrow",

  -- ─── Column width (Cmd+Option+W) ───
  ["window resize"] = "cmd + alt - w",
  ["window shrink"] = "cmd + alt + shift - w",
  ["window fullwidth"] = "cmd + alt - m",

  -- ─── Workspaces (Ctrl+Option+↑/↓ = cycle dynamic rows; Shift = move & follow) ───
  ["window virtual north"] = "ctrl + alt - uparrow",
  ["window virtual south"] = "ctrl + alt - downarrow",
  ["window virtualmove north"] = "ctrl + alt + shift - uparrow",
  ["window virtualmove south"] = "ctrl + alt + shift - downarrow",
  ["window focus managed"] = "cmd + alt - tab",
  -- Workspace rows are created on demand (south past the last row spawns one)
  -- and reaped when empty; the 3-finger vertical swipe also cycles them.

  -- ─── Displays (Cmd+Ctrl lane, native fork commands) ───
  -- Focus prev/next IS the mouse warp (focus_follows_mouse picks it up).
  -- Move prev/next follows; ...send stays on the source display.
  ["mouse previousdisplay"] = "cmd + ctrl - leftarrow",
  ["mouse nextdisplay"] = "cmd + ctrl - rightarrow",
  ["window previousdisplay"] = "cmd + ctrl + shift - leftarrow",
  ["window nextdisplay"] = "cmd + ctrl + shift - rightarrow",
  ["window previousdisplaysend"] = "cmd + ctrl + alt - leftarrow",
  ["window nextdisplaysend"] = "cmd + ctrl + alt - rightarrow",

  -- ─── Window state ───
  ["window manage"] = "cmd + alt - v",           -- toggle tiled/floating
  ["window stack"] = "cmd + alt - o",            -- stack into the neighbour column
  ["window unstack"] = "cmd + alt + shift - o",  -- pull out of a stack into its own column
  ["window center"] = "cmd + alt - space",
  ["window snap"] = "cmd + alt + shift - space", -- snap an overflowing window into view
  ["window equalize"] = "cmd + alt + shift - e",
  ["window balance"] = "cmd + alt - b",          -- all columns match the focused width
  ["window copyrule"] = "cmd + alt + shift - c",

  -- ─── Misc ───
  ["restart"] = "cmd + alt + shift - r",
  ["quit"] = "cmd + alt + ctrl - q",
}

paneru.setup {
  -- ─── Global options ───
  options = {
    focus_follows_mouse = true,
    -- Daemon-native pointer follow: Paneru warps to the window itself on
    -- keyboard-driven focus changes (including display moves), in sync with
    -- its own animation. A helper warp on top lands late and re-triggers
    -- focus as a visible second step — so display moves perform no warp.
    mouse_follows_focus = true,
    -- Horizontally stacked (side-by-side) monitors: arrange displays
    -- vertically in macOS, set this to -1 so edge crossings feel left/right.
    horizontal_mouse_warp = -1,
    horizontal_mouse_warp_offset = 0,
    preset_column_widths = { 0.3, 0.5, 1.0 },
    animation_speed = 12.0,
    -- Lazy expose: at 0.0 any hidden fraction forces the window into view on
    -- focus change, which can re-fire mid-arrival as strips reflow (extra
    -- corrective scrolls on top of the animated flight). 1.0 only exposes
    -- fully-hidden windows; arrival rests looser but quieter.
    window_hidden_ratio = 1.0,
    -- Off: no auto-centering scroll on focus changes. Display moves then
    -- play as the daemon's single native motion instead of arrival scroll
    -- plus re-centering steps; center manually with Cmd+Option+Space.
    auto_center = false,
    create_virtual_workspace_automatically = true,
    reap_empty_workspaces = true,
    window_resize_cycle = true,
  },

  -- ─── Screen padding (outer gaps; Paneru has no inner-gap option) ───
  padding = { top = 15, bottom = 15, left = 15, right = 15 },

  -- ─── Swipe & gestures ───
  swipe = {
    continuous = true,  -- page-flip: a swipe lands exactly on the next window
    sensitivity = 0.35,
    deceleration = 4.0,
    gesture = {
      fingers_count = 3,
      direction = "Natural",
      vertical = true,
    },
    scroll = { modifier = "cmd + alt" },
  },

  -- ─── Decorations ───
  -- Menu-bar workspace indicator is OFF by default: the status item hosts a
  -- live NSView, and AppKit's menu-bar replicant redraw loop starves the run
  -- loop that services Paneru's CGEventTap, so macOS disables the tap and
  -- keybindings silently stop working after leaving native fullscreen.
  -- Upstream fix: karinushka/paneru#390 (merged to main after v0.5.0). Keep
  -- workspace_menu_status = false until a release ships it; flipping it to
  -- true needs a `paneru restart`.
  decorations = {
    workspace_menu_status = false,
    workspace_popup_status = true,
    menu = {
      indicator = { style = "paged", format = "default", font_size = 13.0 },
    },
    inactive = { dim = { opacity = 0.0, opacity_night = 0.0 } },
    active = {
      border = {
        enabled = true,
        color = "#2b303c",
        opacity = 0.84,
        width = 4.0,
        radius = "auto",
      },
    },
  },

  bindings = BINDINGS,

  -- ─── Window rules ───
  windows = {
    calculator = { title = ".*", bundle_id = "com.apple.calculator", floating = true },
    preferences = { title = "Preferences", floating = true },
    -- Firefox: external links spawn a new window carrying Firefox's own
    -- restored size hint, which lands slightly off the column grid and
    -- overlaps the neighbour. Force the initial column ratio so every
    -- main window tiles at grid width; small popups/dialogs are left to
    -- the spawn handler below (size-gated) so they can still float.
    firefox = { title = ".*", bundle_id = "org.mozilla.firefox", width = 0.5, horizontal_padding = 8, vertical_padding = 8 },
    -- Inner gaps: Paneru has no global inner-gap option, so this applies
    -- per-window padding to every tiled window.
    default = { title = ".*", horizontal_padding = 8, vertical_padding = 8 },
  },

  -- ─── Session restore (startup-only) ───
  restore = {
    enabled = true,
    startup_grace_ms = 2000,
    missing_windows = "ignore",
  },
}

-- ─── Module search path ───
-- Kept for future lib/ modules. Display navigation is native in the
-- iv-lite/paneru fork (window/mouse previousdisplay), so lib/displays.lua,
-- lib/query.lua and lib/log.lua are gone — no require here.

-- ─── Firefox external-link fix ───
-- A link clicked in another app spawns a Firefox window carrying Firefox's
-- own restored size hint, which lands slightly off the column grid and
-- overlaps the neighbour (seen live: x=-3 w=1664 next to x=1661 w=1684 on
-- a 3360px display — abutting instead of gapped). The static `firefox`
-- rule above pins the initial ratio; this handler re-pins it at spawn
-- time so the size hint can't win. Small popups/dialogs (< 800x600) are
-- left alone so they can still float.
paneru.on("window_spawned", paneru.match({ bundle = "org.mozilla.firefox" }), function(event, ws)
  local frame = event.frame or {}
  if (frame.width or 0) < 800 or (frame.height or 0) < 600 then return end
  local id = event.window_id
  local ok, res = pcall(function()
    local next_ws = ws:manage(id)
    next_ws = next_ws:sink(id)
    return next_ws:width(id, 0.5)
  end)
  if ok then return res end
  pcall(paneru.log, "firefox spawn fix failed: " .. tostring(res))
end)

-- ─── Keybindings ───
-- Display focus/move are plain BINDINGS-table entries above (native
-- previousdisplay/nextdisplay in the iv-lite fork — true inverses on any
-- number of displays, empty displays included). The ↑/↓ warps below are
-- extra chords onto the same mouse commands, kept from the previous setup.
paneru.bind("cmd + ctrl - uparrow", function() paneru.mouse.next_display() end)
paneru.bind("cmd + ctrl - downarrow", function() paneru.mouse.previous_display() end)

-- Cmd+Ctrl+T opens a new Ghostty window on every press: AppleScript
-- `new terminal` (Ghostty 1.3.0+) creates a window in the running instance
-- (or launches it when it isn't running); if that fails, fall back to plain
-- `open -a`, which at least activates/opens Ghostty.
paneru.bind("cmd + ctrl - t", function()
  local ok, res = pcall(paneru.exec, "/usr/bin/osascript",
    { "-e", 'tell application "Ghostty" to new terminal' })
  if not ok or type(res) ~= "table" or res.code ~= 0 then
    pcall(paneru.exec, "/usr/bin/open", { "-a", "Ghostty" })
  end
end)

-- Workspace rows (window virtual north/south, window virtualmove north/south)
-- are plain BINDINGS-table entries above: Paneru already restores the right
-- scroll position after a virtual-workspace switch on its own (a one-tick-
-- delayed EnsureVisibleMarker correction, see ecs/layout.rs upstream) — an
-- extra `window snap` here used to race that native correction and caused a
-- visible jitter on arrival, without fixing anything the native correction
-- doesn't already handle.

-- Cmd+Shift+? (slash key) opens the shortcut cheat sheet: regenerate the JSON
-- from BINDINGS above, then show it in mac-cheatsheet-viewer.
paneru.bind("cmd + shift - slash", function()
  paneru.exec(os.getenv("HOME") .. "/.config/mac-scrolling-wm/helpers/display-shortcuts")
end)