-- Paneru config — niri-like sliding strip. Modifier lanes:
-- Cmd+Option = columns, Ctrl+Option = dynamic workspace rows,
-- Cmd+Ctrl = displays, Cmd+Shift+? = shortcut cheat sheet.
-- Generated by paneru-wm-installer. Edit freely; live reload is on.
--
-- All Paneru keybindings live in BINDINGS below (command vs chord);
-- helpers/generate-shortcuts-json turns this table into the
-- mac-cheatsheet-viewer JSON.

local BINDINGS = {
  -- ─── Window focus (Cmd+Option+Arrows) ───
  ["window focus west"] = "cmd + alt - leftarrow",
  ["window focus east"] = "cmd + alt - rightarrow",
  ["window focus north"] = "cmd + alt - uparrow",
  ["window focus south"] = "cmd + alt - downarrow",

  -- ─── Move window (Cmd+Option+Shift+Arrows) ───
  ["window swap west"] = "cmd + alt + shift - leftarrow",
  ["window swap east"] = "cmd + alt + shift - rightarrow",
  ["window swap north"] = "cmd + alt + shift - uparrow",
  ["window swap south"] = "cmd + alt + shift - downarrow",

  -- ─── Column width (Cmd+Option+W) ───
  ["window resize"] = "cmd + alt - w",
  ["window shrink"] = "cmd + alt + shift - w",
  ["window fullwidth"] = "cmd + alt - m",

  -- ─── Workspaces (Ctrl+Option+↑/↓ = cycle dynamic rows; Shift = move & follow) ───
  ["window virtual north"] = "ctrl + alt - uparrow",
  ["window virtual south"] = "ctrl + alt - downarrow",
  ["window virtualmove north"] = "ctrl + alt + shift - uparrow",
  ["window virtualmove south"] = "ctrl + alt + shift - downarrow",
  ["window focus managed"] = "cmd + alt - tab",
  -- Workspace rows are created on demand (south past the last row spawns one)
  -- and reaped when empty; the 3-finger vertical swipe also cycles them.

  -- ─── Displays: navigation is handled by function binds below (they add a
  -- full-width maximize before the hop). Mouse warp stays here: ↑ = next. ───
  ["mouse nextdisplay"] = "cmd + ctrl - uparrow",

  -- ─── Window state ───
  ["window manage"] = "cmd + alt - v",           -- toggle tiled/floating
  ["window stack"] = "cmd + alt - o",            -- stack into the neighbour column
  ["window unstack"] = "cmd + alt + shift - o",  -- pull out of a stack into its own column
  ["window center"] = "cmd + alt - space",
  ["window snap"] = "cmd + alt + shift - space", -- snap an overflowing window into view
  ["window equalize"] = "cmd + alt + shift - e",
  ["window balance"] = "cmd + alt - b",          -- all columns match the focused width
  ["window copyrule"] = "cmd + alt + shift - c",

  -- ─── Misc ───
  ["restart"] = "cmd + alt + shift - r",
  ["quit"] = "cmd + alt + ctrl - q",
}

paneru.setup {
  -- ─── Global options ───
  options = {
    focus_follows_mouse = true,
    mouse_follows_focus = true,
    -- Horizontally stacked (side-by-side) monitors: arrange displays
    -- vertically in macOS, set this to -1 so edge crossings feel left/right.
    horizontal_mouse_warp = -1,
    horizontal_mouse_warp_offset = 0,
    preset_column_widths = { 0.3, 0.5, 1.0 },
    animation_speed = 12.0,
    auto_center = false,
    create_virtual_workspace_automatically = true,
    reap_empty_workspaces = true,
    window_resize_cycle = true,
  },

  -- ─── Screen padding (outer gaps; Paneru has no inner-gap option) ───
  padding = { top = 15, bottom = 15, left = 15, right = 15 },

  -- ─── Swipe & gestures ───
  swipe = {
    continuous = false,  -- page-flip: a swipe lands exactly on the next window
    sensitivity = 0.35,
    deceleration = 4.0,
    gesture = {
      fingers_count = 3,
      direction = "Natural",
      vertical = true,
    },
    scroll = { modifier = "cmd + alt" },
  },

  -- ─── Decorations ───
  -- Menu-bar workspace indicator is OFF by default: the status item hosts a
  -- live NSView, and AppKit's menu-bar replicant redraw loop starves the run
  -- loop that services Paneru's CGEventTap, so macOS disables the tap and
  -- keybindings silently stop working after leaving native fullscreen.
  -- Upstream fix: karinushka/paneru#390 (merged to main after v0.5.0). Keep
  -- workspace_menu_status = false until a release ships it; flipping it to
  -- true needs a `paneru restart`.
  decorations = {
    workspace_menu_status = false,
    workspace_popup_status = true,
    menu = {
      indicator = { style = "paged", format = "default", font_size = 13.0 },
    },
    inactive = { dim = { opacity = 0.0, opacity_night = 0.0 } },
    active = {
      border = {
        enabled = true,
        color = "#2b303cd6",
        opacity = 1.0,
        width = 4.0,
        radius = "auto",
      },
    },
  },

  bindings = BINDINGS,

  -- ─── Window rules ───
  windows = {
    calculator = { title = ".*", bundle_id = "com.apple.calculator", floating = true },
    preferences = { title = "Preferences", floating = true },
    -- Inner gaps: Paneru has no global inner-gap option, so this applies
    -- per-window padding to every tiled window.
    default = { title = ".*", horizontal_padding = 8, vertical_padding = 8 },
  },

  -- ─── Session restore (startup-only) ───
  restore = {
    enabled = true,
    startup_grace_ms = 2000,
    missing_windows = "ignore",
  },
}

-- ─── Display navigation ───
-- Cmd+Ctrl+←/→ shift focus to another display without moving the window,
-- using geometric display order (sorted by macOS arrangement position).
-- Cmd+Ctrl+Shift+←/→ moves the focused window to the other display and
-- follows it, with maximize-before-move. With 2 displays this is a single
-- nextdisplay hop. With 3+ displays the helper probes paneru's internal
-- (Bevy/CGDirectDisplayID) display order on first use by moving the
-- focused window through each display once, caches the mapping in
-- paneru.state, and computes the exact hop count on subsequent moves.

local function filled(ws, wid)
  local win, disp = ws:window(wid), ws:display_of(wid)
  if not win or not disp then return true end
  return win.frame.width >= disp.width - 32
end

-- ─── Geometric display ordering (used by focus-only and cache validation) ───
local function ordered_displays(ws)
  local displays = {}
  for _, w in ipairs(ws:windows()) do
    local d = ws:display_of(w.id)
    if d and not displays[d.id] then
      displays[d.id] = { id = d.id, x = d.x, y = d.y }
    end
  end
  local ids = {}
  for id in pairs(displays) do ids[#ids + 1] = id end
  table.sort(ids, function(a, b)
    if displays[a].y ~= displays[b].y then return displays[a].y < displays[b].y end
    return displays[a].x < displays[b].x
  end)
  return ids
end

local function focused_on_display(ws, display_id)
  for _, w in ipairs(ws:windows()) do
    local d = ws:display_of(w.id)
    if d and d.id == display_id and w.focused then return w.id end
  end
  for _, w in ipairs(ws:windows()) do
    local d = ws:display_of(w.id)
    if d and d.id == display_id then return w.id end
  end
end

local function focus_display(ws, target)
  local focused = ws:focused()
  if not focused then return end
  local cur = ws:display_of(focused)
  local ids = ordered_displays(ws)
  if not cur or #ids < 2 then return end
  local idx
  for i, id in ipairs(ids) do if id == cur.id then idx = i break end end
  if not idx then return end
  local n = #ids
  local step = (target == "previous") and (n - 1) or 1
  local target_id = ids[((idx - 1 + step) % n) + 1]
  local win = focused_on_display(ws, target_id)
  if win then return ws:focus(win) end
end

-- ─── Bevy-order probe + cache (for move shortcuts with 3+ displays) ───
-- Paneru's `window nextdisplay` follows the internal Bevy entity spawn
-- order (driven by CGGetActiveDisplayList), which does NOT match the
-- geometric display arrangement.  To compute the correct hop count for
-- "previous"/"next" we must first discover this order by observing where
-- the window lands after each hop.  The result is cached in paneru.state
-- and invalidated when the set of display IDs changes (hot-plug).
local CACHE_KEY = "display_bevy_order"
local PROBE_KEY = "display_bevy_probe"

local function read_cache()
  return paneru.state.get(CACHE_KEY)
end

local function write_cache(geo, bevy)
  paneru.state.set(CACHE_KEY, { geometric = geo, bevy = bevy })
end

local function validate_cache(ws, cache)
  if not cache then return false end
  local cur = {}
  for _, id in ipairs(ordered_displays(ws)) do cur[id] = true end
  for _, id in ipairs(cache.geometric) do
    if not cur[id] then return false end
  end
  for id in pairs(cur) do
    local found = false
    for _, cid in ipairs(cache.geometric) do
      if cid == id then found = true; break end
    end
    if not found then return false end
  end
  return true
end

-- Move using the cached Bevy↔geometric mapping.
local function move_with_cache(ws, target, cache)
  local wid = ws:focused()
  if not wid then return end
  local cur = ws:display_of(wid)
  if not cur then return end
  local geo_idx
  for i, id in ipairs(cache.geometric) do
    if id == cur.id then geo_idx = i; break end
  end
  if not geo_idx then return end
  local n = #cache.geometric
  local step = (target == "previous") and (n - 1) or 1
  local target_id = cache.geometric[((geo_idx - 1 + step) % n) + 1]
  local bevy_cur, bevy_tgt
  for i, id in ipairs(cache.bevy) do
    if id == cur.id then bevy_cur = i end
    if id == target_id then bevy_tgt = i end
  end
  if not bevy_cur or not bevy_tgt then return end
  local hops = (bevy_tgt - bevy_cur) % n
  if hops == 0 then return end
  if not filled(ws, wid) then paneru.run("window fullwidth") end
  for _ = 1, hops do paneru.run("window nextdisplay") end
end

-- Start the probe: move the focused window through all displays once,
-- recording each landing display via the window_moved handler.
local function start_probe(ws, target)
  local wid = ws:focused()
  if not wid then return end
  local cur = ws:display_of(wid)
  if not cur then return end
  local n = #ordered_displays(ws)
  if n < 2 then return end
  paneru.state.set(PROBE_KEY, {
    window_id = wid,
    order = { cur.id },
    total = n,
    target = target,
  })
  paneru.run("window nextdisplay")
end

-- Probe observer: records where the window lands after each hop and, once
-- all displays have been seen, builds the cache and dispatches the real move.
paneru.on("window_moved", function(event, ws)
  local probe = paneru.state.get(PROBE_KEY)
  if not probe then return end
  if event.window_id ~= probe.window_id then return end
  local disp = ws:display_of(event.window_id)
  if not disp then
    paneru.state.set(PROBE_KEY, nil)
    return
  end
  table.insert(probe.order, disp.id)
  if #probe.order >= probe.total then
    local geo = ordered_displays(ws)
    write_cache(geo, probe.order)
    paneru.state.set(PROBE_KEY, nil)
    move_with_cache(ws, probe.target, { geometric = geo, bevy = probe.order })
  else
    paneru.state.set(PROBE_KEY, probe)
    paneru.run("window nextdisplay")
  end
end)

-- Move shortcut: N≤2 is a single hop (no probe needed); N≥3 uses the
-- cache-or-probe path.
local function move_to_display(ws, target)
  local n = #ordered_displays(ws)
  if n <= 2 then
    local wid = ws:focused()
    if wid and not filled(ws, wid) then paneru.run("window fullwidth") end
    paneru.run("window nextdisplay")
    return
  end
  local cache = read_cache()
  if cache and validate_cache(ws, cache) then
    move_with_cache(ws, target, cache)
  else
    start_probe(ws, target)
  end
end

-- ─── Keybindings ───
-- Focus only: window stays put, no maximize.
paneru.bind("cmd + ctrl - leftarrow", function(ws) return focus_display(ws, "previous") end)
paneru.bind("cmd + ctrl - rightarrow", function(ws) return focus_display(ws, "next") end)
-- Move window + follow, with maximize-before-move.
paneru.bind("cmd + ctrl + shift - leftarrow", function(ws) move_to_display(ws, "previous") end)
paneru.bind("cmd + ctrl + shift - rightarrow", function(ws) move_to_display(ws, "next") end)

-- Cmd+Shift+? (slash key) opens the shortcut cheat sheet: regenerate the JSON
-- from BINDINGS above, then show it in mac-cheatsheet-viewer.
paneru.bind("cmd + shift - slash", function()
  paneru.exec(os.getenv("HOME") .. "/.config/mac-scrolling-wm/helpers/display-shortcuts")
end)