[workspace]
switch = "Unassigned"
moveTo = "Unassigned"
backAndForth = "Control+Option+Tab"
next = "Command+Option+Down Arrow"
previous = "Command+Option+Up Arrow"

[focus]
left = "Command+Left Arrow"
down = "Command+Down Arrow"
up = "Command+Up Arrow"
right = "Command+Right Arrow"
previous = "Command+Option+Tab"
columnFirst = "Option+Home"
columnLast = "Option+End"
column.1 = "Control+Option+1"
column.2 = "Control+Option+2"
column.3 = "Control+Option+3"
column.4 = "Control+Option+4"
column.5 = "Control+Option+5"
column.6 = "Control+Option+6"
column.7 = "Control+Option+7"
column.8 = "Control+Option+8"
column.9 = "Control+Option+9"
monitorNext = "Command+Control+Right Arrow"
monitorPrevious = "Command+Control+Left Arrow"
monitorLast = "Control+Command+Grave"

[move]
left = "Command+Shift+Left Arrow"
down = "Command+Shift+Down Arrow"
up = "Command+Shift+Up Arrow"
right = "Command+Shift+Right Arrow"
windowToWorkspaceUp = "Command+Option+Shift+Up Arrow"
windowToWorkspaceDown = "Command+Option+Shift+Down Arrow"
columnToWorkspaceUp = "Control+Option+Shift+Page Up"
columnToWorkspaceDown = "Control+Option+Shift+Page Down"
columnLeft = "Control+Option+Shift+Left Arrow"
columnRight = "Control+Option+Shift+Right Arrow"
columnToFirst = "Control+Option+Home"
columnToLast = "Control+Option+End"
windowToWorkspaceOnMonitor.1.left = "Command+Control+Shift+Left Arrow"
windowToWorkspaceOnMonitor.1.right = "Command+Control+Shift+Right Arrow"
windowToWorkspaceOnMonitor.1.up = "Command+Control+Shift+Up Arrow"
windowToWorkspaceOnMonitor.1.down = "Command+Control+Shift+Down Arrow"

[layout]
toggleFullscreen = "Option+Return"
toggleNativeFullscreen = "Unassigned"
toggleColumnTabbed = "Option+T"
cycleColumnWidthForward = "Command+Option+W"
cycleColumnWidthBackward = "Command+Option+Shift+W"
toggleColumnFullWidth = "Command+Option+M"
expandColumnToAvailable = "Control+Option+F"
decreaseColumnWidth = "Option+Minus"
increaseColumnWidth = "Option+Equal"
decreaseWindowHeight = "Option+Shift+Minus"
increaseWindowHeight = "Option+Shift+Equal"
resetWindowHeight = "Control+Option+R"
balanceSizes = "Command+Option+B"
toggleFocusedFloating = "Command+Option+V"
raiseAllFloating = "Option+Shift+R"

[ui]
commandPalette = "Control+Option+Space"
menuAnywhere = "Control+Option+M"
toggleOverview = "Option+Shift+O"